### ISSUE TITLE
The decompiler hangs when trying to decompile the main function in the gnu binutils binary

### ISSUE THREAD

**Issue by febnug** [radareorg/r2dec-js#223] opened 2020-08-11 15:53 UTC
So I want to test the analysis of the gnu binutils binary file (`/bin/ls`), when I try to decompile the `main` function using the `pdda @ main` command, because a few seconds the decompile result doesn't appear, I'm forced to interrupt.

My `radare2` version :
<pre>
% r2 -v
radare2 4.5.0 0 @ linux-x86-32 git.4.5.0
commit: HEAD build: 2020-08-11__21:51:04
</pre>
---
<pre>
% r2 -AA /bin/ls
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references
Warning: aao experimental on 32bit binaries
[x] Check for vtables
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
[x] Finding function preludes
[x] Enable constraint types analysis for variables
 -- :(){ :|:& };:
[0x0804bee9]> pdda @ main
^C

r2dec has crashed (info:  @ ).
Please report the bug at https://github.com/wargio/r2dec-js/issues
Use the option '--issue' or the command 'pddi' to generate 
the needed data for the issue.
[0x0804bee9]> pddi > file.json
[0x0804bee9]>
</pre>

Normal when decompile simple `Hello World` program 
<pre>
% r2 -AA hello
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references
Warning: aao experimental on 32bit binaries
[x] Check for vtables
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
[x] Finding function preludes
[x] Enable constraint types analysis for variables
 -- what happens in #radare, stays in #radare
[0x080482d0]> pdda @ main
    ; assembly                                   | /* r2dec pseudo code output */
                                                 | /* hello @ 0x80483c2 */
                                                 | #include <stdint.h>
                                                 |  
    ; (fcn) main ()                              | int32_t main (char ** argv) {
                                                 |     int32_t var_4h;
    0x080483c2 lea ecx, [esp + 4]                |     ecx = &argv;
    0x080483c6 and esp, 0xfffffff0               |     
    0x080483c9 push dword [ecx - 4]              |     
    0x080483cc push ebp                          |     
    0x080483cd mov ebp, esp                      |     
    0x080483cf push ecx                          |     
    0x080483d0 sub esp, 4                        |     
    0x080483d3 sub esp, 0xc                      |     
    0x080483d6 push 0x8048470                    |     
    0x080483db call 0x80482a0                    |     puts ("hello");
    0x080483e0 add esp, 0x10                     |     
    0x080483e3 mov eax, 0                        |     eax = 0;
    0x080483e8 mov ecx, dword [ebp - 4]          |     ecx = var_4h;
    0x080483eb leave                             |     
    0x080483ec lea esp, [ecx - 4]                |     esp = ecx - 4;
    0x080483ef ret                               |     return eax;
                                                 | }
[0x080482d0]>
</pre>
[file.zip](https://github.com/radareorg/r2dec-js/files/5057969/file.zip)

**Comment by wargio** [comment] 2020-08-11 16:29
please do
```
s main
pdda > file.json
```

**Comment by febnug** [comment] 2020-08-11 18:03
hmm.. file.json file output blank

**Comment by wargio** [comment] 2020-08-12 08:35
can you run the same again with `e r2dec.debug = true` and give me the crash dump? ore even better the file. (ps: how big is it?)

**Comment by febnug** [comment] 2020-08-13 08:23
this is file attachment, result of `e r2dec.debug = true` , i'm not sure i get a crash dump (dump manually using `gcore` maybe ?)

[file.zip](https://github.com/radareorg/r2dec-js/files/5067928/file.zip)

**Comment by wargio** [comment] 2020-08-13 08:35
ok, so the issue is that r2 is providing a bad json when calling `pxj`.
i'm patching thins on r2dec side, since i never can trust what r2 returns.

**Comment by wargio** [comment] 2020-08-13 08:37
Fixed by https://github.com/radareorg/r2dec-js/commit/4b1f41a7b33736c6d36761ce4925e9b41e79fe33

**Comment by wargio** [comment] 2020-08-13 08:38
please now update your r2dec version with `r2pm install r2dec`

**Closed by wargio** 2020-08-13 08:37 UTC

**Comment by febnug** [comment] 2020-08-13 09:08
cool
